Added syntax check for file passed to vidoas script using -n flag.
Restored vidoas script to /usr/local/bin/ from /usr/local/sbin/
to insure it is in common user path.

diff --git a/vidoas b/vidoas
--- a/vidoas
+++ b/vidoas
@@ -188,6 +188,10 @@ fi
 
 if ${noop}
 then
+    if ! doas -C "${DOAS_CONF}"
+    then
+        die "${DOAS_CONF} contains syntax errors."
+    fi
     warn 'OK: Prerequisite checks passed'
     exit 0
 fi
